export const SET_INCREMENT_PAGE = "SET_INCREMENT_PAGE";
export const SET_DECREMENT_PAGE = "SET_DECREMENT_PAGE";
export const SET_MAXIMUM_PAGES = "SET_MAXIMUM_PAGES";
export const SET_PAGE_SIZE_TO_ONE = "SET_PAGE_TO_ONE";
export const SET_PAGE_SIZE_TO_FOUR = "SET_PAGE_SIZE_TO_FOUR";
export const SET_PAGE_SIZE_TO_SIX = "SET_PAGE_SIZE_TO_SIX";
export const SET_PAGE_SIZE_TO_DEFAULT = "SET_PAGE_SIZE_TO_DEFAULT";
