export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const COUNT_CART_ITEMS = "COUNT_CART_ITEMS";
export const CLEAR_CART_ITEMS_AFTER_ORDER = "CLEAR_CART_ITEMS_AFTER_ORDER";
export const CLEAR_CART = "CLEAR_CART";
export const REMOVE_ONE_CART_ITEM = "REMOVE_ONE_CART_ITEM";
