// request
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_FAILURE = "CREATE_BOOK_FAILURE";
// input
export const BOOK_TITLE_INPUT = "BOOK_TITLE_INPUT";
export const BOOK_WRITTER_INPUT = "BOOK_WRITTER_INPUT";
export const BOOK_GENRE_INPUT = "BOOK_GENRE_INPUT";
export const BOOK_YEAR_INPUT = "BOOK_YEAR_INPUT";
export const BOOK_PRICE_INPUT = "BOOK_PRICE_INPUT";
export const BOOK_QUANTITY_INPUT = "BOOK_QUANTITY_INPUT";
