export const GET_WISHLIST_ITEMS = "GET_WISHLIST_ITEMS";
export const POST_NEW_WISHLIST_ITEM = "POST_NEW_WISHLIST_ITEM";
export const DELETE_ALL_WISHLIST_ITEMS = "DELETE_ALL_WISHLIST_ITEMS";
export const DELETE_ONE_ITEM_FROM_WISHLIST = "DELETE_ONE_ITEM_FROM_WISHLIST";
