export const LOAD_BOOKS = "LOAD_BOOKS";
export const LOADING_BOOKS = "LOADING_BOOKS";
export const SELECT_BOOK = "SELECT_BOOK";
export const GET_TOTAL_SUM = "GET_TOTAL_SUM";
export const REMOVE_BOOK_FROM_CART = "REMOVE_BOOK_FROM_CART";
export const CLEAR_ALL_BOOKS_FROM_CART = "CLEAR_ALL_BOOKS_FROM_CART";
export const TOGGLE_LOADER_TRUE = "TOGGLE_LOADER_TRUE";
export const TOGGLE_LOADER_FALSE = "TOGGLE_LOADER_FALSE";
