export const LOAD_BOOKS = "LOAD_BOOKS";
export const SELECT_BOOK = "SELECT_BOOK";
export const GET_TOTAL_SUM = "GET_TOTAL_SUM";
export const REMOVE_BOOK_FROM_CART = "REMOVE_BOOK_FROM_CART";
export const CLEAR_ALL_BOOKS_FROM_CART = "CLEAR_ALL_BOOKS_FROM_CART";
