export const FORM_COMPLETE = "FORM_COMPLETE";
export const POST_REGISTRATION = "POST_REGISTRATION";
// USER INFO
export const SET_EMAIL_ADDRESS = "SET_EMAIL_ADDRESS";
export const SET_PASSWORD = "SET_PASSWORD";
// PERSONAL INFO
export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_USERNAME = "SET_USERNAME";
export const SET_AGE = "SET_AGE";
export const SET_GENDER = "SET_GENDER";
// SHIPPING INFO
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_CITY = "SET_CITY";
export const SET_COUNTRY = "SET_COUNTRY";
export const SET_POSTAL_CODE = "SET_POSTAL_CODE";
export const SET_PHONE = "SET_PHONE";
// REGISTER REQUEST
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
// STEP
export const STEP_INCREMENT = "STEP_INCREMENT";
export const STEP_DECREMENT = "STEP_DECREMENT";
// VALIDATE
export const VALIDATE_TRUE = "VALIDATE_TRUE";
export const VALIDATE_FALSE = "VALIDATE_FALSE";
