export const TYPE_EMAIL_ADDRESS = "TYPE_EMAIL_ADDRESS";
export const TYPE_PASSWORD = "TYPE_PASSWORD";
export const FORM_COMPLETE = "FORM_COMPLETE";
export const POST_REGISTRATION = "POST_REGISTRATION";
