export const SELECT_BOOK = "SELECT_BOOK";
export const ADD_INDEX = "ADD_INDEX";
export const REMOVE_BOOK = "REMOVE_BOOK";
export const CLEAR_BOOKS = "CLEAR_BOOKS";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const REMOVE_DUPLICATE = "REMOVE_DUPLICATE";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const ADD_BOOK_TO_CART = "ADD_BOOK_TO_CART";
export const DELETE_PREVIOUS_BOOK = "DELETE_PREVIOUS_BOOK";
// Snackbar
export const IS_ADDED_FALSE = "IS_ADDED_FALSE";
export const ITEM_DUPLICATE_TRUE = "ITEM_DUPLICATE_TRUE";
export const ITEM_DUPLICATE_FALSE = "ITEM_DUPLICATE_FALSE";
