// Books
export const ADD_INDEX = "ADD_INDEX";
export const ADD_BOOK_TO_CART = "ADD_BOOK_TO_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
// Checkout
export const CLEAR_BOOKS = "CLEAR_BOOKS";
// Snackbar
export const IS_ADDED_FALSE = "IS_ADDED_FALSE";
export const ITEM_DUPLICATE_TRUE = "ITEM_DUPLICATE_TRUE";
export const ITEM_DUPLICATE_FALSE = "ITEM_DUPLICATE_FALSE";
